# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np




### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [95]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [97]:
print(A.shape)
print(A.ndim)
print(A.dtype.name)
print(A.itemsize)


(3, 5)
2
int64
8


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [100]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
print(B)
print(C)
print(B * C)
print(B - C)
print(B @ C)





[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [104]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print(np.exp(B))
print(B.min)
print(B.min(axis=1))
print(B.min(axis=0))
print(np.argmin(B))
print(np.argmin(B,axis=1))
print(B.sum)
print(B.sum(axis=0))
print(np.mean(B,axis=0))
print(np.median(B,axis=0))








[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
<built-in method min of numpy.ndarray object at 0x00000273C99D3150>
[1 4 7]
[1 2 3]
0
[0 0 0]
<built-in method sum of numpy.ndarray object at 0x00000273C99D3150>
[12 15 18]
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [108]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [110]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [115]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [117]:
for i in A:
  print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [119]:
for element in A:
    for variable in element:
        print(variable)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [122]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print(a.shape)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
(30,)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


It means it has three dimensions.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [128]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [131]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [133]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [139]:
### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [141]:
x = np.array([[4 , 3]])
print(x)

[[4 3]]


In [143]:
print(x.ndim)

2


In [145]:
print(5*x)

[[20 15]]


In [147]:
print(3*x)

[[12  9]]


In [149]:
print((5*x) + (3*x))

[[32 24]]


In [151]:
print(8*x)

[[32 24]]


In [153]:
print((4*x) -(x))

[[12  9]]


In [155]:
print(x.T)

[[4]
 [3]]


In [157]:
from numpy import linalg
print(linalg.norm(x))

5.0


In [169]:
v= np.array([[3, 7, 0, 11]]).T
print(v)


[[ 3]
 [ 7]
 [ 0]
 [11]]


In [171]:
print(x.ndim)

2


In [175]:
print(2*v)

[[ 6]
 [14]
 [ 0]
 [22]]


In [179]:
print((4*v) -(2*v))

[[ 6]
 [14]
 [ 0]
 [22]]


In [181]:
print(linalg.norm(v))

13.379088160259652


In [183]:
v1 = np.array([[4, 3, 1, 5]])
v2 = np.array([[2, 3, 1, 1]])
print(linalg.norm(v1))

7.14142842854285


In [187]:
print(linalg.norm(v1) - linalg.norm(v2))

3.2684450823354334


In [45]:
A = np.array([[2 , 1, -1, ],[1 , -1, 1]])
print(A)
B = np.array([[4, -2, 1],[2, -4, -2]])
print(B)
C = np.array([[1,2],[2, 1]])
print(C)
D = np.array([[3, 4],[4, 3]])
print(D)
E = np.array([[1],[2]])
print(E)
I = np.array([[1,0],[0,1]])
print(I)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]
[[1 0]
 [0 1]]


In [15]:
print(2*A)

[[ 4  2 -2]
 [ 2 -2  2]]


In [19]:
print(B - (2*A))

[[ 0 -4  3]
 [ 0 -2 -4]]


In [23]:
print((3*C) -(2*E))

[[ 1  4]
 [ 2 -1]]


In [25]:
print((2*D) -(3*C))

[[3 2]
 [0 3]]


In [49]:
print((D.T) +(2*D))

[[ 9 12]
 [12  9]]


In [51]:
print((2*C.T) -(2*D.T))

[[-4 -4]
 [-4 -4]]


A.T -B 

# Ii did not work because they have two different shapes

In [ ]:
A @ C # Got a syntaxerror

In [71]:
print(C @ D)

[[11 10]
 [10 11]]


In [73]:
print(C @ B)

[[  8 -10  -3]
 [ 10  -8   0]]


In [75]:
print(C @ I)

[[1 2]
 [2 1]]


In [77]:
print(A @ B.T)

[[5 2]
 [7 4]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [47]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [51]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [53]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
